server:
  servlet:
    session:
      timeout: 20m
  error:
    whitelabel:
      enabled: false
  port: 8080
spring:
  docker:
    compose:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    banner-mode: off
  security:
    user:
      name: admin
      password: 1234
  thymeleaf:
    prefix : classpath:/templates/
    cache: false
  #    suffix: .html
  #    cache: false
  datasource:
    hikari:
      pool-name: Leader
      auto-commit: false
      jdbc-url: jdbc:postgresql://postgres-db:5432/mart
      username: admin
      password: admin
      maximum-pool-size: 10
      minimum-idle: 10
      driver-class-name: org.postgresql.Driver
      follower:
        pool-name: Follower
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://postgres-db:5432/mart
        username: admin
        password: admin
        minimum-idle: 5
        maximum-pool-size: 5

  jpa:  # DB (none, create, create-drop, update, validate)
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: create-drop


  cache:
    type: redis
  redis:
    cache:
      host: redis-db
      port: 6379

baobab:
  scan:
    packages:
      - com.hun.market

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cloud:
  aws:
    s3:
      bucket: 123132
    credentials:
      access-key: 123123
      secret-key: 132131
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
